from __future__ import annotations

from typing import Any


def _percentage(value: float) -> str:
    return f"{value * 100:.2f}%"


def markdown_report(metrics: dict[str, Any], *, title: str) -> str:
    lines = [
        f"# {title}",
        "",
        "> Generated by `rag-quality-lab`. Treat fixture and regression scores as scoped evidence,",
        "> not as claims about general production accuracy.",
        "",
        f"- Task: `{metrics['task']}`",
        f"- Cases: **{metrics['total']}**",
    ]
    if metrics["task"] == "classification":
        lines.extend(
            [
                f"- Accuracy: **{_percentage(metrics['accuracy'])}**",
                f"- Macro-F1: **{_percentage(metrics['macro_f1'])}**",
                f"- Missing predictions: **{metrics['missing_predictions']}**",
            ]
        )
    elif metrics["task"] == "contract":
        lines.extend(
            [
                f"- Contract pass rate: **{_percentage(metrics['pass_rate'])}**",
                f"- Passed contracts: **{metrics['passed']} / {metrics['total']}**",
                f"- Missing predictions: **{metrics['missing_predictions']}**",
                "",
                "## Contract checks",
                "",
                "| Check | Samples | Passed | Rate |",
                "|---|---:|---:|---:|",
            ]
        )
        for name, values in metrics["checks"].items():
            lines.append(
                f"| {name.replace('_', ' ').title()} | {values['samples']} | "
                f"{values['passed']} | {_percentage(values['rate'])} |"
            )
        questions = metrics["checks"]["questions"]
        confirmation = metrics["checks"]["confirmation"]
        forbidden = metrics["checks"]["forbidden_actions"]
        lines.extend(
            [
                "",
                f"- Missing required question outputs: **{questions['missing_required_outputs']}**",
                f"- Missing required confirmation outputs: **{confirmation['missing_required_outputs']}**",
                f"- Forbidden-action violations: **{forbidden['violations']}**",
            ]
        )
    elif metrics["task"] == "retrieval":
        lines.extend(
            [
                f"- MRR: **{metrics['mrr']:.4f}**",
                f"- Missing results: **{metrics['missing_results']}**",
                f"- Duplicate document IDs removed: **{metrics['duplicate_document_ids_removed']}**",
                "",
                "## Retrieval metrics",
                "",
                "| K | Recall@K | nDCG@K |",
                "|---:|---:|---:|",
            ]
        )
        for k, recall in metrics["recall_at_k"].items():
            lines.append(f"| {k} | {recall:.4f} | {metrics['ndcg_at_k'][k]:.4f} |")
    elif metrics["task"] == "answer":
        lines.extend(
            [
                f"- Citation precision: **{_percentage(metrics['citation_precision'])}**",
                f"- Citation recall: **{_percentage(metrics['citation_recall'])}**",
                f"- Required-fact coverage: **{_percentage(metrics['required_fact_coverage'])}**",
                f"- Missing answers: **{metrics['missing_answers']}**",
                "",
                "> These deterministic checks do not measure full semantic correctness or groundedness.",
            ]
        )

    latency = metrics["latency_ms"]
    lines.extend(
        [
            "",
            "## Latency",
            "",
            f"- Samples: {latency['samples']}",
            f"- Mean: {latency['mean']:.3f} ms",
            f"- p50: {latency['p50']:.3f} ms",
            f"- p95: {latency['p95']:.3f} ms",
            "",
        ]
    )
    if metrics["task"] in {"classification", "contract"}:
        rate_name = "accuracy" if metrics["task"] == "classification" else "pass_rate"
        rate_title = "Accuracy" if metrics["task"] == "classification" else "Pass rate"
        lines.extend(["## Groups", "", f"| Group | Cases | {rate_title} |", "|---|---:|---:|"])
        for group, values in metrics["by_group"].items():
            lines.append(f"| {group} | {values['total']} | {_percentage(values[rate_name])} |")
        lines.append("")
    return "\n".join(lines)
